---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: my-logs-pv
spec:
  storageClassName: hostpathlogs
  capacity:
    storage: 2Gi
  accessModes:
  - ReadWriteMany
  hostPath:
    path: "$AIRFLOW_HOME/airflow-logs-chart-testing"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: my-logs-pvc
spec:
  storageClassName: hostpathlogs
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
